//Each hive has many resources, departments, and jobs

public class Hive {
	//Your physical resources
	private Resource pollen;
	private Resource nectar;
	private Resource honey;
	private Resource wax;
	private Resource xp;
	//Your abstract resources
	private Resource hygiene;
	private Resource queenHealth;
	private Resource strength;
	//Temperature (NOT a resource!)
	private float hiveTemp;
	private int heatTempConst; //some constant to scale heat to normal temperatures
	private int tempFoodConst; //some constant to scale temperature regulation to food cost
	private int bigTempDiff; //significant temperature difference constant
	//Your departments (see if you can fit in an array/arraylist?)
	private Department nurse;
	private Department forager;
	private Department guard;
	private Department waxMason;
	private Department houseBee;
	private Department fanner;
	private Department drone;
	private Department cluster;
	//Your Jobs (nomenclature: departmentResourceInfluenced)
	private Job nurseQueenHealth = new Job(nurse);
	private Job foragerNectar = new Job(forager);
	private Job foragerPollen = new Job(forager);
	private Job guardStrength = new Job(guard);
	private Job waxMasonWax = new Job(waxMason);
	private Job houseBeeHygiene = new Job(houseBee);
	private Job fannerHoney = new Job(fanner);
	private Job droneXP = new Job(drone);
	private Job idle = new Job(cluster);
	//The Nursery
	private Nursery nursery;
		
	//A lovely constructor or two?
	
	//Some methods
	public void update(){
		updateJobs();
			//add all produced resources
			//find foodCost for this
			//find heat generated by this
			//find foodCost for HVAC-ing the hive
			//adjust temperature accordingly
		updateNursery();
			//This could be replaced with a simple nursery.update()
		update
		//Update catastrophe timer
		//Deal with warnings/memos (like starvation, overheating, etc.)
	}
	
	//updateJobs() updates all job-related things
	private void updateJobs(){
		//add all produced resources to the hive
		queenHealth.setAmount(nurseQueenHealth.getResource());
		strength.setAmount(guardStrength.getResource());
		hygiene.setAmount(houseBeeHygiene.getResource());
		nectar.add(foragerNectar.getResource());
		pollen.add(foragerPollen.getResource());
		wax.add(waxMasonWax.getResource());
		xp.add(droneXP.getResource());
		//Honey updating is complicated since it depends on and influences nectar
		if(nectar.getAmount() > fannerHoney.getResource()){
			nectar.sub(fannerHoney.getResource());
			honey.add(fannerHoney.getResource() / honey.getPotency());
		} else if(nectar.getAmount() > 0){
			nectar.setAmount(0);
			honey.add(nectar.getAmount() / honey.getPotency());
			//Throw "Unused Fanners!" warning
		}
		
		//find foodCost for this (by department)
		int totalFoodCost = nurse.getFoodCost() +
							forager.getFoodCost() +
							guard.getFoodCost() +
							waxMason.getFoodCost() +
							houseBee.getFoodCost() +
							fanner.getFoodCost() +
							drone.getFoodCost() +
							cluster.getFoodCost();
		//find heat generated by this (by department)
		int totalHeat = nurse.getHeat() +
				forager.getHeat() +
				guard.getHeat() +
				waxMason.getHeat() +
				houseBee.getHeat() +
				fanner.getHeat() +
				drone.getHeat() +
				cluster.getHeat();
		//find foodCost for HVAC-ing the hive
		//...and adjust temperature accordingly
		totalFoodCost += adjustTemp(totalHeat);
		//subtract food
		subFood(totalFoodCost);
	}
	//subFood() takes a foodCost and depletes resources accordingly
	private int subFood(int foodCost){
		if(foodCost <= nectar.getFoodValue()){
			nectar.sub(foodCost / nectar.getPotency());
			foodCost = 0;
		}else{
			foodCost -= nectar.getFoodValue();
			nectar.setAmount(0);
			if(foodCost <= honey.getFoodValue()){
				honey.sub(foodCost / honey.getPotency());
				foodCost = 0;
				//Throw honey warning
			}else{
				foodCost -= honey.getFoodValue();
				honey.setAmount(0);
				//Throw starvation warning
			}
		}
		return foodCost;
	}
	//adjustTemp() adjusts the temperature and returns the foodCost for doing so
	private int adjustTemp(int totalHeat){
		float temp = totalHeat / heatTempConst;
		if(temp - hiveTemp >= bigTempDiff){
			hiveTemp += .1;
			return (int)((temp - hiveTemp) * tempFoodConst);
		}else if(hiveTemp - temp >= bigTempDiff){
			hiveTemp -= .1;
			return (int)((hiveTemp - temp) * tempFoodConst);
		}
		return 0;
	}
	
	//literally just calls nursery.update()
	private void updateNursery(){
		nursery.update();
	}

}
